### ISSUE TITLE
How to use ros-cdk output command

### ISSUE THREAD

**Issue by kucharzyk-sebastian** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#42]
Hi,

I have a problem with using `ros-cdk output` command. I tried using both stack name and stack ID as the argument but it keeps failing.

When I use stack name I get an error:
```
ros-cdk output seku-vs-webrtc-service-china-stateful
fail to get stack events: InvalidParameter The specified parameter StackId is invalid, "null" does not match pattern "^[0-9a-f]{8}[-][0-9a-f]{4}[-][0-9a-f]{4}[-][0-9a-f]{4}[-][0-9a-f]{12}$"., URL: https://ros.aliyuncs.com/?AccessKeyId=<MASKED>&Action=GetStack&Format=JSON&RegionId=eu-west-1&SignatureMethod=HMAC-SHA1&SignatureNonce=<MASKED>&SignatureVersion=1.0&StackId=null&Timestamp=2022-03-30T15%3A15%3A25Z&Version=2019-09-10&Signature=<MASKED>
```
When I use stack ID I get something different:
```
ros-cdk output <MASKED>-<MASKED>-<MASKED>-<MASKED>-<MASKED>
The specific stack doesn't exist, Please check the accuracy of the input stack name!
```

I double-checked the stack name, stack ID and region and all the values I've been providing were correct. Could you advise how to make this command work?

**Comment by Ehzyo** [comment]
I think this may be the same problem as  [How to use ros-cdk generate-stack-file with an account limited to a resource group](https://github.com/aliyun/Resource-Orchestration-Service-Cloud-Development-Kit/issues/40#issuecomment-1083973138).

If `ros-cdk output` supports `--resource-group-id`, it works. Because ROS:ListStacks will use default resource group if ResourceGroupId is not passed. As your stack is in another resource group, the stack cannot be queried. CDK can't get StackId, it becomes null.

We will add this feature in the near future.

**Comment by kucharzyk-sebastian** [comment]
That was the case, I didn't have the `stack.info.json` file on my local machine. Maybe we could add information about it to the error message? Like:
```
The specific stack doesn't exist in the stack.info.json file, Please check the accuracy of the input stack name!
```

**Comment by Ehzyo** [comment]
Thanks for your advice。We will fix it in next release.

**Comment by baichenxu3** [comment]
ros-cdk-cli 1.0.22 is released.  error message problem is fix.
